### ISSUE TITLE
Pause handling issue

### ISSUE THREAD

**Issue by nsqa99** [NishaLab/LTMang#13]
Người dùng ko thể pause khi đã trả lời xong câu hỏi.
Nên **_sửa lại core concept_** hay **_thêm nó là quy tắc chơi_**?

**Comment by NishaLab** [comment]
T nghĩ thêm nó là quy tắc chơi
Bởi nó trả lời rồi thì pause làm gì

**Comment by nsqa99** [comment]
gút chóp
