### ISSUE TITLE
Tính năng game đấu nhiều vòng

### ISSUE THREAD

**Issue by NishaLab** [NishaLab/LTMang#3]
Hiện tại chương trình mới dừng lại ở chơi 1 game
Bây giờ muốn chương trình đọc 1 mảng câu hỏi nhất định từ db và cho người chơi chơi lần lượt từng câu hỏi đó
Thời gian trả lời mỗi câu trung bình là 15s
Cần cài đặt một cơ chế để đồng bộ các biến đếm ngược giữa server và các Client
Sau khi chạy hết câu hỏi thì tiến hành đánh giá và trả kết quá về cho player ( cái này có thể tách làm 1 issue khác cho người khác )

**Comment by nsqa99** [comment]
**Done tasks:** 
- Tính năng game đấu nhiều vòng (duyệt mảng câu hỏi)
- Xử lý cho nhiều client kết nối đến server
- Xử lý server cho phép client kết nối tới để trả lời câu hỏi trong 1 khoảng thời gian nhất định

**Chỉnh sửa từ require:**
- Việc đồng bộ các biến đếm ngược giữa client và server: client sẽ không đếm, chỉ server đếm và gửi thông điệp hết thời gian trả lời câu hỏi đến cho client

**Remaining issues:**
- Chưa handle việc 1 client ngắt kết nối thì game đấu vẫn tiếp tục với các client khác

- Chưa xử lý đáp án, check đúng/sai và trả lại kết quả cho client, mới lưu lại câu trả lời của client vào 1 list.

**New issue đề xuất cho nhóm trưởng:** 

- Tạo thêm các giao diện để người dùng tương tác với server, ví dụ như 1 frame để hiển thị số giây còn lại, frame cho người dùng nhấn nút Bắt đầu và Thoát...

- Việc lưu lại các câu hỏi, session... cái này t nghĩ ông rõ hơn mn về cách hoạt động :D

**Comment by NishaLab** [comment]
Comment:
Ok. Về mấy issue mới về mặt giao diện thì mai t sẽ làm thêm 1 số frame nữa + với viết mấy hàm tính năng lưu cho DB luôn
